import { useEffect, useState } from 'react'
import {
  ArrowRight, Check, Crown, MessageCircle,
  Play, ShieldCheck, Target, Users, X,
} from 'lucide-react'
import './App.css'

const innerCircleUrl = 'https://whop.com/wealthy-visions-academy/wva-inner-circle/'
const Button = ({ children, href = '#coaching', alt = false, gold = false }) => <a className={`btn ${alt ? 'alt' : ''} ${gold ? 'gold' : ''}`} href={href}>{children}<ArrowRight size={16}/></a>
const Head = ({ over, title, copy, center = false }) => <div className={`head ${center ? 'center' : ''}`}><span className="eyebrow">{over}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>
const List = ({ items, muted = false }) => <ul className={`ticks ${muted ? 'muted' : ''}`}>{items.map(x => <li key={x}><Check size={15}/>{x}</li>)}</ul>

const programs = [
  ['ADVANCED 1-ON-1 COACHING',Target,'Six months of personalized development for traders who want direct guidance, trade review, and accountability.',['Six months of 1-on-1 coaching','Customized trading roadmap','Private trade and performance reviews','Risk and psychology coaching','Strategy execution feedback','Direct support and accountability','Lifetime access to WVA programs'],'Apply & Book a Call','#coaching','featured gold','$1,200 · 6 MONTHS'],
  ['INNER CIRCLE',Crown,'Ongoing live education, market preparation, resources, and community accountability.',['Daily live trading sessions','Institutional market bias','Trade setups and breakdowns','Complete course library','Strategy vault and playbooks','Weekly market overview','Replay library and community'],'Join the Inner Circle',innerCircleUrl,'','$79 / MONTH'],
]
function Chart({ large = false }) {
  return <svg className={`chart ${large ? 'large' : ''}`} viewBox="0 0 500 230" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#00ff90" stopOpacity=".24"/><stop offset="1" stopColor="#00ff90" stopOpacity="0"/></linearGradient></defs>{[45,90,135,180].map(y=><line key={y} x1="0" x2="500" y1={y} y2={y}/>)}<path className="area" d="M0 190C50 180 62 126 105 145s58 22 92-20 70 8 104-20 45-95 86-62 60 72 113 12v175H0z"/><path className="price" d="M0 190C50 180 62 126 105 145s58 22 92-20 70 8 104-20 45-95 86-62 60 72 113 12"/>{Array.from({length:16}).map((_,i)=><g key={i} className={i%3 ? 'up':'down'}><line x1={i*31+12} x2={i*31+12} y1={55+(i*29)%105} y2={102+(i*17)%108}/><rect x={i*31+7} y={72+(i*23)%90} width="10" height={25+(i*7)%30}/></g>)}</svg>
}

function Form({ coaching = false, onSubmit }) {
  const params = new URLSearchParams(window.location.search)
  const tracking = ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']
  return <form className={`form ${coaching ? 'typeform' : ''}`} onSubmit={onSubmit}>{tracking.map(key=><input key={key} type="hidden" name={key} value={params.get(key)||''} readOnly/>)}{coaching ? <><div className="form-progress"><span>STEP 1 OF 2</span><i/></div><h3>Tell us where you are in your trading journey.</h3><p>Complete this short application to unlock the private booking calendar.</p><label>What is your full name?<input required placeholder="Type your answer here"/></label><label>What is your best email address?<input required type="email" placeholder="name@email.com"/></label><label>How long have you been trading?<select required defaultValue=""><option value="" disabled>Select your experience</option><option>Under 1 year</option><option>1–3 years</option><option>3+ years</option></select></label><label>What is your primary trading challenge?<textarea required placeholder="Tell Abel what you want help improving..."/></label><button className="btn">Submit & Unlock Calendar <ArrowRight size={16}/></button><small>Your information is used only to evaluate coaching fit and coordinate your call.</small></>:<><div className="form-row"><label>First name<input required placeholder="First name"/></label><label>Email address<input required type="email" placeholder="you@email.com"/></label></div><div className="form-row"><label>Trading experience<select required defaultValue=""><option value="" disabled>Select level</option><option>New trader</option><option>Under 1 year</option><option>1–3 years</option><option>3+ years</option></select></label><label>Primary market<select required defaultValue=""><option value="" disabled>Select market</option><option>Futures</option><option>Forex</option><option>Both</option><option>Still deciding</option></select></label></div><button className="btn">Send Me the Checklist <ArrowRight size={16}/></button></>}</form>
}

function App() {
  const [video,setVideo]=useState(false), [exit,setExit]=useState(false), [apply,setApply]=useState(false)
  const [slide,setSlide]=useState(0), [sent,setSent]=useState('')
  useEffect(()=>{const leave=e=>{if(e.clientY<=0&&!sessionStorage.wvExit){sessionStorage.wvExit='1';setExit(true)}};document.addEventListener('mouseleave',leave);return()=>document.removeEventListener('mouseleave',leave)},[])
  useEffect(()=>{const openApplication=()=>{if(window.location.hash==='#coaching'){setExit(false);setApply(true)}};openApplication();window.addEventListener('hashchange',openApplication);return()=>window.removeEventListener('hashchange',openApplication)},[])
  useEffect(()=>{document.body.style.overflow=(video||exit||apply)?'hidden':''},[video,exit,apply])
  const submit=(e,type)=>{e.preventDefault();setSent(type)}
  const quotes=[
    ['PROCESS STORY','“Add a verified member story about replacing strategy hopping with one documented model.”','Verified name + member since'],
    ['RISK MILESTONE','“Add a genuine testimonial about improved risk consistency, patience, or fewer impulsive trades.”','Verified name + permission'],
    ['VIDEO TESTIMONIAL','Upload a verified member video focused on process, routines, and lessons—not just profit.','Video asset required'],
  ]
  return <div className="site">
    <div className="announce"><span><i/>Enrollment is open for six months of Advanced 1-on-1 Coaching.</span><a href="#coaching">Apply & Book a Call <ArrowRight size={13}/></a></div>

    <main>
      <section className="hero grid-bg" id="home"><div className="glow"/><div className="container hero-grid"><div className="hero-copy"><h1>Watch This Video Before You Buy Another Trading Course or Blow Another Account.</h1><p>Go from confused and inconsistent to trading with a clear strategy, defined rules, stronger risk management, and confidence.</p></div><div className="hero-media"><span className="terminal"><i/> WVA PRIVATE COACHING · PERSONALIZED ROADMAP</span><button className="video" onClick={()=>setVideo(true)}><Chart large/><div className="silhouette"><i/><b/></div><div className="video-copy"><small>FOUNDER PRESENTATION · 08:42</small><strong>The Advanced<br/>Coaching Roadmap</strong><span><Play fill="currentColor"/></span></div></button><small className="risk"><ShieldCheck/> Coaching provides education and accountability—not guaranteed trading outcomes. Trading involves substantial risk.</small></div></div></section>

      <section className="section results" id="results"><div className="container"><Head over="VERIFIED MEMBER PROOF" title="Real Progress From Real Traders" copy="Publish only genuine proof supplied by Wealthy Visions. Every story should show the process behind the milestone." center/><div className="carousel"><button onClick={()=>setSlide((slide+2)%3)}>←</button><article><i>“</i><span>{quotes[slide][0]}</span><blockquote>{quotes[slide][1]}</blockquote><small>{quotes[slide][2]}</small></article><button onClick={()=>setSlide((slide+1)%3)}>→</button></div><div className="awards">{['$1K DAY','$10K DAY','FIRST PROP-FIRM PAYOUT','PROFITABLE MONTH','3-MONTH CONSISTENCY','6-MONTH CONSISTENCY'].map(x=><span key={x}><Crown/>{x}</span>)}</div><p className="disclosure">Testimonials reflect individual experiences. Results are not typical or guaranteed. Performance depends on experience, discipline, risk management, market conditions, and other factors.</p></div></section>

      <section className="section founder" id="about"><div className="container founder-grid"><div className="portrait"><span>AM</span><small>OFFICIAL FOUNDER PHOTO<br/>TO BE SUPPLIED</small><div><b>TRADING SINCE</b><strong>2015</strong></div></div><div><Head over="MEET THE FOUNDER" title="Built by a Trader. Led by an Educator."/><p>Abel Melendez is a professional trader and educator with experience across forex and futures. After beginning in 2015, he transitioned into full-time trading and has educated traders through multiple trading organizations.</p><p>His teaching focuses on liquidity, market structure, fair value gaps, supply and demand, and the practical work of developing independent traders.</p><blockquote>“I created Wealthy Visions because most traders do not need more noise. They need a clear process, honest feedback, repetition, and an environment that holds them accountable. My goal is not to make you dependent on signals. It is to help you better understand the market and your own decision-making.”</blockquote><div className="signature">Abel Melendez <span>— Founder, Wealthy Visions</span></div></div></div></section>

      <section className="section ecosystem grid-bg" id="inner-circle"><div className="container"><Head over="TWO WAYS TO WORK WITH WVA" title="Choose the Support That Fits Your Development." copy="Apply for private one-on-one coaching or join the Inner Circle for live group education, resources, and community." center/><div className="program-grid">{programs.map(([name,Icon,best,items,cta,href,style,price])=><article className={style||''} key={name}>{style?.includes('featured')&&<span className="popular">FLAGSHIP OFFER</span>}<Icon className="program-icon"/><small>{name}</small><h3>{price}</h3><p>{best}</p><List items={items}/><Button alt={!style?.includes('featured')&&!style?.includes('gold')} gold={style?.includes('gold')} href={href}>{cta}</Button>{style?.includes('gold')&&<i className="note">Designed for traders prepared to commit to six months of guided development.</i>}</article>)}</div></div></section>

    </main>

    <footer><div className="container footer-grid"><div><strong>WEALTHY VISIONS LLC</strong><p>Trading education, live market experience, and structured trader development.</p><span className="social"><Users/><Play/><MessageCircle/></span></div><div><b>Programs</b><a href="#coaching">Advanced Coaching</a><a href={innerCircleUrl}>Inner Circle</a></div><div><b>Company</b><a href="#about">About Abel</a><a href="#results">Results</a><a href="mailto:contact@example.com">Contact</a></div><div><b>Legal</b><a href="#">Terms of Service</a><a href="#">Privacy Policy</a><a href="#">Refund Policy</a><a href="#">Risk Disclosure</a><a href="#">Earnings Disclaimer</a></div></div><div className="container legal"><b>TRADING RISK DISCLOSURE</b><p>Trading futures, forex, and other financial instruments involves substantial risk and may not be suitable for every person. Participants can lose some or all of their capital. Past performance, testimonials, hypothetical results, simulated results, and educational examples do not guarantee future performance. Wealthy Visions LLC provides education and community services and does not provide personalized financial, legal, or tax advice.</p><p><strong>CFTC RULE 4.41:</strong> Hypothetical or simulated performance results have certain limitations. Unlike an actual performance record, simulated results do not represent actual trading. Since the trades have not been executed, results may have under- or over-compensated for market factors, such as lack of liquidity. Simulated trading programs are also generally designed with the benefit of hindsight. No representation is made that any account will or is likely to achieve profits or losses similar to those shown.</p><span>© {new Date().getFullYear()} Wealthy Visions LLC. All rights reserved.</span></div></footer>

    <a className="mobile-cta" href="#coaching">Apply & Book a Call <ArrowRight/></a>
    {apply&&<div className="modal" role="dialog" aria-modal="true" aria-label="Advanced coaching application"><div className="application-modal"><button className="close" onClick={()=>{setApply(false);history.replaceState(null,'',window.location.pathname+window.location.search)}}><X/></button>{sent==='coach'?<div className="calendar-gate"><div className="form-progress complete"><span>STEP 2 OF 2</span><i/></div><Check/><h3>Application complete. Book your call.</h3><p>Your calendar embed will appear here after the booking link is connected.</p><div className="calendar-placeholder"><span>PRIVATE BOOKING CALENDAR</span><strong>Connect your Calendly, Cal.com, or Typeform scheduling URL</strong><button disabled>Calendar link required</button></div></div>:<Form coaching onSubmit={e=>submit(e,'coach')}/>}</div></div>}
    {video&&<div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setVideo(false)}><X/></button><div className="video-modal"><div><Play fill="currentColor"/><h3>The Advanced Coaching Roadmap</h3><p>Connect the official Abel Melendez video embed before publishing.</p></div></div></div>}
    {exit&&<div className="modal" role="dialog" aria-modal="true"><div className="exit"><button className="close" onClick={()=>setExit(false)}><X/></button><span className="eyebrow">BEFORE YOU GO</span><h2>Ready for Direct Trading Guidance?</h2><p>Complete the short coaching application to unlock the private call-booking calendar.</p><Button href="#coaching">Apply & Book a Call</Button><button className="text-btn" onClick={()=>setExit(false)}>No thanks, I’ll keep browsing</button></div></div>}
  </div>
}

export default App
