import { useEffect, useState } from 'react'
import {
  ArrowRight, Check, Crown, Play, ShieldCheck, Target, X,
} from 'lucide-react'
import './App.css'

const innerCircleUrl = 'https://whop.com/checkout/plan_tvEu6o0oWLJYQ'
const Button = ({ children, href = '#coaching', alt = false, gold = false }) => <a className={`btn ${alt ? 'alt' : ''} ${gold ? 'gold' : ''}`} href={href}>{children}<ArrowRight size={16}/></a>
const Head = ({ over, title, copy, center = false }) => <div className={`head ${center ? 'center' : ''}`}><span className="eyebrow">{over}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>
const List = ({ items, muted = false }) => <ul className={`ticks ${muted ? 'muted' : ''}`}>{items.map(x => <li key={x}><Check size={15}/>{x}</li>)}</ul>

const programs = [
  ['INNER CIRCLE',Crown,'Ongoing live education, market preparation, resources, and community accountability.',['Daily live trading sessions','Institutional market bias','Trade setups and breakdowns','Complete course library','Strategy vault and playbooks','Weekly market overview','Replay library and community'],'Join the Inner Circle',innerCircleUrl,'','$79 / MONTH'],
  ['ADVANCED 1-ON-1 COACHING',Target,'Six months of personalized development for traders who want direct guidance, trade review, and accountability.',['Six months of 1-on-1 coaching','Customized trading roadmap','Private trade and performance reviews','Risk and psychology coaching','Strategy execution feedback','Direct support and accountability','Lifetime access to WVA programs'],'Apply & Book a Call','#coaching','featured gold','$1,200 · 6 MONTHS'],
]

function Form({ coaching = false, onSubmit }) {
  const params = new URLSearchParams(window.location.search)
  const tracking = ['utm_source','utm_medium','utm_campaign','utm_content','utm_term']
  return <form className={`form ${coaching ? 'typeform' : ''}`} onSubmit={onSubmit}>{tracking.map(key=><input key={key} type="hidden" name={key} value={params.get(key)||''} readOnly/>)}{coaching ? <><div className="form-progress"><span>STEP 1 OF 2</span><i/></div><h3>Tell us where you are in your trading journey.</h3><p>Complete this short application to unlock the private booking calendar.</p><label>What is your full name?<input required placeholder="Type your answer here"/></label><label>What is your best email address?<input required type="email" placeholder="name@email.com"/></label><label>How long have you been trading?<select required defaultValue=""><option value="" disabled>Select your experience</option><option>Under 1 year</option><option>1–3 years</option><option>3+ years</option></select></label><label>What is your primary trading challenge?<textarea required placeholder="Tell Abel what you want help improving..."/></label><button className="btn">Submit & Unlock Calendar <ArrowRight size={16}/></button><small>Your information is used only to evaluate coaching fit and coordinate your call.</small></>:<><div className="form-row"><label>First name<input required placeholder="First name"/></label><label>Email address<input required type="email" placeholder="you@email.com"/></label></div><div className="form-row"><label>Trading experience<select required defaultValue=""><option value="" disabled>Select level</option><option>New trader</option><option>Under 1 year</option><option>1–3 years</option><option>3+ years</option></select></label><label>Primary market<select required defaultValue=""><option value="" disabled>Select market</option><option>Futures</option><option>Forex</option><option>Both</option><option>Still deciding</option></select></label></div><button className="btn">Send Me the Checklist <ArrowRight size={16}/></button></>}</form>
}

function App() {
  const [video,setVideo]=useState(false), [apply,setApply]=useState(false)
  const [sent,setSent]=useState('')
  useEffect(()=>{const openApplication=()=>{if(window.location.hash==='#coaching')setApply(true)};openApplication();window.addEventListener('hashchange',openApplication);return()=>window.removeEventListener('hashchange',openApplication)},[])
  useEffect(()=>{document.body.style.overflow=(video||apply)?'hidden':''},[video,apply])
  const submit=(e,type)=>{e.preventDefault();setSent(type)}
  return <div className="site">

    <main>
      <section className="hero grid-bg" id="home"><div className="glow"/><div className="container hero-grid"><div className="hero-copy"><h1>Tired of Blowing Accounts and Starting Over? <em>Watch the Video Below.</em></h1><p>Go from confused and inconsistent to trading with a clear strategy, defined rules, stronger risk management, and confidence.</p></div><div className="hero-media"><button className="video" onClick={()=>setVideo(true)} aria-label="Play the Wealthy Visions video"><img src="/vsl-thumbnail.png?v=3" alt="Why you keep blowing accounts — watch the video"/><span className="play-pulse" aria-hidden="true"><Play fill="currentColor" size={36}/></span></button><small className="risk"><ShieldCheck/> Coaching provides education and accountability—not guaranteed trading outcomes. Trading involves substantial risk.</small></div></div></section>

      <section className="section founder" id="about"><div className="container founder-grid"><div className="portrait"><img src="/abel-melendez-founder.png" alt="Abel Melendez, founder of Wealthy Visions"/><div><b>TRADING SINCE</b><strong>2015</strong></div></div><div><Head over="MEET THE FOUNDER" title="Helping Traders Replace Confusion With Structure."/><p>Abel Melendez is a trader, educator, and founder of Wealthy Visions Academy. Since beginning his trading journey in 2015, he has gained experience across forex and futures while helping traders understand liquidity, market structure, risk management, and disciplined execution.</p><p>After seeing traders repeatedly struggle with strategy hopping, emotional decisions, and blown accounts, Abel created Wealthy Visions to provide direct guidance, honest feedback, and accountability—not more noise.</p><p>His mission is to help traders refine what they already know, correct the habits holding them back, and build a clear process they can execute independently.</p><div className="signature">Abel Melendez <span>— Founder, Wealthy Visions</span></div></div></div></section>

      <section className="section ecosystem grid-bg" id="inner-circle"><div className="container"><Head over="TWO WAYS TO WORK WITH WVA" title="Choose the Support That Fits Your Development." copy="Apply for private one-on-one coaching or join the Inner Circle for live group education, resources, and community." center/><div className="program-grid">{programs.map(([name,Icon,best,items,cta,href,style,price])=><article className={style||''} key={name}>{style?.includes('featured')&&<span className="popular">FLAGSHIP OFFER</span>}<Icon className="program-icon"/><small>{name}</small><h3>{price}</h3><p>{best}</p><List items={items}/><Button alt={!style?.includes('featured')&&!style?.includes('gold')} gold={style?.includes('gold')} href={href}>{cta}</Button>{style?.includes('gold')&&<i className="note">Designed for traders prepared to commit to six months of guided development.</i>}</article>)}</div></div></section>

    </main>

    <footer><div className="container legal"><b>TRADING RISK DISCLOSURE</b><p>Trading futures, forex, and other financial instruments involves substantial risk and may not be suitable for every person. Participants can lose some or all of their capital. Past performance, testimonials, hypothetical results, simulated results, and educational examples do not guarantee future performance. Wealthy Visions LLC provides education and community services and does not provide personalized financial, legal, or tax advice.</p><p><strong>CFTC RULE 4.41:</strong> Hypothetical or simulated performance results have certain limitations. Unlike an actual performance record, simulated results do not represent actual trading. Since the trades have not been executed, results may have under- or over-compensated for market factors, such as lack of liquidity. Simulated trading programs are also generally designed with the benefit of hindsight. No representation is made that any account will or is likely to achieve profits or losses similar to those shown.</p><span>© {new Date().getFullYear()} Wealthy Visions LLC. All rights reserved.</span></div></footer>

    {apply&&<div className="modal" role="dialog" aria-modal="true" aria-label="Advanced coaching application"><div className="application-modal"><button className="close" onClick={()=>{setApply(false);history.replaceState(null,'',window.location.pathname+window.location.search)}}><X/></button>{sent==='coach'?<div className="calendar-gate"><div className="form-progress complete"><span>STEP 2 OF 2</span><i/></div><Check/><h3>Application complete. Book your call.</h3><p>Your calendar embed will appear here after the booking link is connected.</p><div className="calendar-placeholder"><span>PRIVATE BOOKING CALENDAR</span><strong>Connect your Calendly, Cal.com, or Typeform scheduling URL</strong><button disabled>Calendar link required</button></div></div>:<Form coaching onSubmit={e=>submit(e,'coach')}/>}</div></div>}
    {video&&<div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setVideo(false)}><X/></button><div className="video-modal"><iframe src="https://player.vimeo.com/video/1217517866?autoplay=1&title=0&byline=0&portrait=0" title="Wealthy Visions VSL" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/></div></div>}
  </div>
}

export default App
